/**
 * Home Page Component for a Next.js Application
 *
 * This is the main page of a Next.js application that renders multiple sections, 
 * including a Hero, About, Features, Floating Image, and Contact.
 * 
 * Features:
 * - Uses `Metadata` from Next.js for SEO optimization.
 * - Utilizes Tailwind CSS for responsive styling.
 * - Includes multiple reusable components.
 *
 * Tailwind Classes Explained:
 * - `relative` → Positions this element relative to its normal position.
 * - `min-h-screen` → Ensures the main container is at least as tall as the viewport.
 * - `w-screen` → Forces the container width to span the entire viewport width.
 * - `overflow-x-hidden` → Hides horizontal scrolling caused by animated or overflowing elements.
 */

import type { Metadata } from "next"; // Import Metadata type from Next.js
import Hero from "./components/Hero"; // Hero section component
import About from "./components/About"; // About section component
import Contact from "./components/Contact"; // Contact section component
import Features from "./components/Features"; // Features section component
import FloatingImage from "./components/FloatingImage"; // Floating image animation component

/**
 * Metadata for SEO (Search Engine Optimization)
 * 
 * - `title`: Sets the page title shown in the browser tab.
 * - `description`: Provides a brief description for search engines and social media previews.
 */
export const metadata: Metadata = {
  title: "Create Next App", // Customize this for your project
  description: "Generated by create next app", // Modify for better SEO
};

/**
 * Home Page Component
 * 
 * This functional component is the default export for the `/` route.
 * It renders various sections to build the homepage layout.
 */
export default function Home() {
  return (
    /**
     * The `main` container that wraps all sections of the homepage.
     * 
     * Tailwind CSS Classes Used:
     * - `relative` → Positions the element relative to its normal flow, allowing absolute children.
     * - `min-h-screen` → Ensures this section is at least as tall as the viewport height.
     * - `w-screen` → Forces this section to take up the full width of the screen.
     * - `overflow-x-hidden` → Prevents unwanted horizontal scrolling due to overflowing animations.
     */
    <main className="relative min-h-screen w-screen overflow-x-hidden">
      {/* Hero Section - The first visual section of the page */}
      <Hero />

      {/* About Section - Information about the website or company */}
      <About />

      {/* Features Section - Showcasing key features of the product/service */}
      <Features />

      {/* Floating Image Section - Adds a dynamic floating image effect */}
      <FloatingImage />

      {/* Contact Section - Includes a form or details for reaching out */}
      <Contact />
    </main>
  );
}
